In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
uniqueemo=df['emotion'].unique()
uniqueemo

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [6]:
emo_num={}
i=0
for emo in uniqueemo:
  emo_num[emo]=i
  i+=1

df['emotion']=df['emotion'].map(emo_num)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [7]:
df['text'] = df['text'].apply(lambda x: x.lower())
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

TO remove punction we also have function like string.punctuation

In [8]:
import string
def remove_punc(text):
  return text.translate(str.maketrans('','',string.punctuation))
  #return text.translate(str.maketrans('', '',string.punctuation))

In [9]:
df['text']=df['text'].apply(remove_punc)

In [10]:
def remove_num(text):
  new=""
  for i in text:
    if not i.isdigit():
      new= new +i
  return new

df['text']=df['text'].apply(remove_num)
#print(new)

In [11]:
def remove_emojis(text):
  new = " "
  for i in text:
    if i.isascii():
      new += i
  return new.strip()

df['text'] = df['text'].apply(remove_emojis)

In [12]:
import nltk

In [13]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [28]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [17]:
stop_words=set(stopwords.words('english'))
len(stop_words)

198

In [18]:
df.loc[1]

text       i can go from feeling so hopeless to so damned...
emotion                                                    0
Name: 1, dtype: object

tokenization-convert string to single token
Not to use split is that it cant diff punctuation marks

In [29]:
def remove(txt):
  words=word_tokenize(txt)
  return words

In [30]:
df['tokenized_text'] = df['text'].apply(remove)
df.head()

,text,emotion,tokenized_text
0,i didnt feel humiliated,0,"[i, didnt, feel, humiliated]"
1,i can go from feeling so hopeless to so damned...,0,"[i, can, go, from, feeling, so, hopeless, to, ..."
2,im grabbing a minute to post i feel greedy wrong,1,"[im, grabbing, a, minute, to, post, i, feel, g..."
3,i am ever feeling nostalgic about the fireplac...,2,"[i, am, ever, feeling, nostalgic, about, the, ..."
4,i am feeling grouchy,1,"[i, am, feeling, grouchy]"

In [31]:
def remove_stopwords(text_tokens):
  return [word for word in text_tokens if word not in stop_words]

df['cleaned_text'] = df['tokenized_text'].apply(remove_stopwords)
df.head()

,text,emotion,tokenized_text,cleaned_text
0,i didnt feel humiliated,0,"[i, didnt, feel, humiliated]","[didnt, feel, humiliated]"
1,i can go from feeling so hopeless to so damned...,0,"[i, can, go, from, feeling, so, hopeless, to, ...","[go, feeling, hopeless, damned, hopeful, aroun..."
2,im grabbing a minute to post i feel greedy wrong,1,"[im, grabbing, a, minute, to, post, i, feel, g...","[im, grabbing, minute, post, feel, greedy, wrong]"
3,i am ever feeling nostalgic about the fireplac...,2,"[i, am, ever, feeling, nostalgic, about, the, ...","[ever, feeling, nostalgic, fireplace, know, st..."
4,i am feeling grouchy,1,"[i, am, feeling, grouchy]","[feeling, grouchy]"